name: Dev Version Increment

on:
  push:
    branches:
      - dev

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git config --global user.name 'velocirrabit'
      - run: git config --global user.email 'ci@velocirabbit.it'
      - run: npm version patch -m "[DEV] %s"
      - run: git push
